export const batterHeaderDataList = [
  { text: '順位', value: 'RANK' },
  { text: '選 手 名', value: 'NAME' },
  { text: '所属球団', value: 'TEAM' },
  { text: '打率', value: 'AVG' },
  { text: '試合数', value: 'GAMES' },
  { text: '打席数', value: 'PA' },
  { text: '打点', value: 'AB' },
  { text: '安打数', value: 'H' },
  { text: '二塁打', value: '2B' },
  { text: '三塁打', value: '3B' },
  { text: '本塁打', value: 'HR' },
  { text: '塁打数', value: 'TB' },
  { text: '打点数', value: 'RBI' },
  { text: '得点数', value: 'RS' },
  { text: '三振数', value: 'SO' },
  { text: '四球数', value: 'BB' },
  { text: '死球', value: 'HBP' },
  { text: '犠打数', value: 'SH' },
  { text: '犠飛数', value: 'SF' },
  { text: '盗塁数', value: 'SB' },
  { text: '盗塁死数', value: 'CS' },
  { text: '併殺打数', value: 'GDP' },
  { text: '出塁率', value: 'OBP' },
  { text: '長打率', value: 'SLG' },
  { text: 'OPS', value: 'OPS' },
  { text: '得点圏', value: 'RISP' },
  { text: '失策数', value: 'E' }
]

export const pitcherHeaderDataList = [
  { text: '順位', value: 'RANK' },
  { text: '選 手 名', value: 'NAME' },
  { text: '所属球団', value: 'TEAM' },
  { text: '防御率', value: 'ERA' },
  { text: '登板試合数', value: 'APP' },
  { text: '先発出場数', value: 'GS' },
  { text: '完投数', value: 'CG' },
  { text: '完封数', value: 'SHO' },
  { text: 'QS', value: 'QS' },
  { text: '勝利数', value: 'W' },
  { text: '負け数', value: 'L' },
  { text: 'ホールド数', value: 'HLD' },
  { text: 'ホールドポイント', value: 'HP' },
  { text: 'セーブ数', value: 'SV' },
  { text: '勝率', value: 'WPCT' },
  { text: '投球回', value: 'IP' },
  { text: '被安打数', value: 'H' },
  { text: '被本塁打数', value: 'HR' },
  { text: '奪三振', value: 'SO' },
  { text: '奪三振率', value: 'SO/9' },
  { text: '与四球数', value: 'BB' },
  { text: '与死球数', value: 'HBP' },
  { text: '暴投数', value: 'WP' },
  { text: 'ボーク数', value: 'BK' },
  { text: '失点数', value: 'R' },
  { text: '自責点数', value: 'ER' },
  { text: '被打率', value: 'AVG' },
  { text: 'K/BB', value: 'K/BB' },
  { text: 'WHIP', value: 'WHIP' }
]
